### ISSUE TITLE
Failed ExceptionHandlingTest#test04_02_webApplicationHandling in Support Spring IO Platform Athens-SR1

### ISSUE THREAD

**Issue by bturamatuyu** [terasolunaorg/terasoluna-gfw-functionaltest#513] opened 2016-11-29 08:08 UTC
## Description
I try to run gfw-functionaltest with terasoluna-gfw build with Spring IO Athens-SR1

Tested branch is below：
issues/563_Spring_IO_PF_Athens_For_1.4.1.BUILD-SNAPSHOT

but,I found following error：
- Test Class：

org.terasoluna.gfw.functionaltest.app.exceptionhandling.ExceptionHandlingTest

- Test Method：

test04_02_webApplicationHandling

- Travis-ci Log:
test04_02_webApplicationHandling(org.terasoluna.gfw.functionaltest.app.exceptionhandling.ExceptionHandlingTest)  Time elapsed: 0.317 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "Servlet Error..." but: was "System Error..."
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.terasoluna.gfw.functionaltest.app.exceptionhandling.ExceptionHandlingTest.test04_02_webApplicationHandling(ExceptionHandlingTest.java:417)

## Possible Solutions
N/A

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.3.0.RELEASE

## Issue Links
* #

**Comment by kazuki43zoo** [comment] 2016-11-29 14:20
## Root Cause for this issue

Since Spring 4.3, there are possible that a sub class of `java.lang.Error` will be handled by `HandlerExceptionResolver` instead of servlet container.

For details see https://jira.spring.io/browse/SPR-11106.

**Comment by bthondasui** [comment] 2016-12-21 06:54
In order to pass the tests of  #514 , #515 , #516 , and #526 ,
the expected value of the test was changed from Servlet Error to System Error by provisional countermeasure.

In order to make the same movement as existing,
Add an exception setting of NestedServletException to SystemExceptionResolver in spring-mvc.xml.
(It has been verified that it becomes a Servlet Error when a subclass of java.lang.Error is thrown.)

Under consideration about countermeasures.

**Comment by btyoshikawaa** [comment] 2017-01-05 07:19
Workaround is merged. But we need to consider an optimal method.

**Comment by kazuki43zoo** [comment] 2017-02-05 17:02
@bthondasui 

> Workaround is merged. But we need to consider an optimal method.

Please fix workaround.

**Comment by btyoshikawaa** [comment] 2017-02-10 11:53
See https://github.com/terasolunaorg/guideline/issues/2368

**Closed by btyoshikawaa** 2017-02-10 11:53 UTC
Labels: 5.3.0, in review, Must
